#!/usr/bin/env bash
#
# scripts/download-models.sh
#
# Fetch the Kokoro TTS model weights and voice embeddings into
# upstream-kokoro/Resources/, then verify SHA256 hashes against a committed
# manifest. This is a thin wrapper around the upstream repo's existing
# download script — the upstream script is canonical; we add verification
# and staging for DMG packaging.
#
# Usage:
#   scripts/download-models.sh              # fetch + verify
#   VERIFY_ONLY=1 scripts/download-models.sh   # skip fetch, re-verify
#
# Exit codes:
#   0  — success (all required files present, checksums match or baseline written)
#   1  — main model file missing after fetch
#   2  — prerequisite tooling missing
#
# See scripts/model-checksums.txt for the manifest format.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
UPSTREAM_DIR="$REPO_ROOT/upstream-kokoro"
RES_DIR="$UPSTREAM_DIR/Resources"
CHECKSUMS="$SCRIPT_DIR/model-checksums.txt"

say() { printf '[download-models] %s\n' "$*"; }
warn() { printf '[download-models] WARN: %s\n' "$*" >&2; }
die()  { printf '[download-models] ERROR: %s\n' "$*" >&2; exit "${2:-1}"; }

# ---------- prerequisite checks -----------------------------------------
command -v shasum >/dev/null 2>&1 || die "shasum not found (part of macOS base)" 2
command -v make    >/dev/null 2>&1 || die "make not found"                      2

# ---------- fetch ---------------------------------------------------------
if [[ "${VERIFY_ONLY:-0}" != "1" ]]; then
  if [[ ! -d "$UPSTREAM_DIR" ]]; then
    die "upstream-kokoro missing at $UPSTREAM_DIR (did you clone with --recurse-submodules?)"
  fi
  say "delegating to upstream: cd upstream-kokoro && make download-models"
  ( cd "$UPSTREAM_DIR" && make download-models )
  say "upstream download complete."
fi

# ---------- existence check ----------------------------------------------
MAIN_MODEL="$RES_DIR/kokoro-v1_0.safetensors"
if [[ ! -f "$MAIN_MODEL" ]]; then
  die "main model file missing: $MAIN_MODEL" 1
fi

VOICE_DIR="$RES_DIR/voices"
if [[ ! -d "$VOICE_DIR" ]]; then
  warn "voices/ directory is empty or missing at $VOICE_DIR"
fi

# ---------- hash computation --------------------------------------------
declare -a CURRENT_HASHES=()

# Main safetensors
H=$(shasum -a 256 "$MAIN_MODEL" | awk '{print $1}')
CURRENT_HASHES+=("$H  kokoro-v1_0.safetensors")

# Voices
shopt -s nullglob
for f in "$VOICE_DIR"/*.safetensors; do
  name="voices/$(basename "$f")"
  H=$(shasum -a 256 "$f" | awk '{print $1}')
  CURRENT_HASHES+=("$H  $name")
done
shopt -u nullglob

say "computed hashes for ${#CURRENT_HASHES[@]} file(s)"

# ---------- verify / write baseline --------------------------------------
#
# The manifest lives at scripts/model-checksums.txt and is committed with
# `TODO` placeholders on first-time checkout. If every entry is TODO (or
# the file has no concrete hashes), we write the current hashes as the
# baseline and exit 0. On subsequent runs we warn on mismatch — upstream
# HuggingFace revisions may legitimately update files, and we don't want
# a hash mismatch to break contributor workflows. Reproducible release
# builds should bump the manifest intentionally when they do.

is_baseline_empty=true
if [[ -f "$CHECKSUMS" ]]; then
  if grep -Eq '^[0-9a-f]{64}  ' "$CHECKSUMS"; then
    is_baseline_empty=false
  fi
fi

if $is_baseline_empty; then
  say "manifest has no concrete hashes yet — writing baseline to $CHECKSUMS"
  {
    printf '# freekoko model checksums (SHA-256)\n'
    printf '# Generated by scripts/download-models.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# Verify with: cd upstream-kokoro/Resources && shasum -a 256 -c %s\n' \
      "$(realpath --relative-to="$RES_DIR" "$CHECKSUMS" 2>/dev/null || echo "$CHECKSUMS")"
    printf '#\n'
    printf '# To refresh: delete the hash lines below and re-run scripts/download-models.sh\n'
    printf '#\n\n'
    printf '%s\n' "${CURRENT_HASHES[@]}"
  } > "$CHECKSUMS"
  say "baseline manifest written (${#CURRENT_HASHES[@]} entries)."
else
  say "verifying against existing manifest..."
  mismatch=0
  while IFS= read -r line; do
    # Skip comments/blank
    [[ -z "${line// }" ]] && continue
    [[ "$line" =~ ^# ]] && continue

    expected_hash=$(awk '{print $1}' <<<"$line")
    expected_path=$(awk '{$1=""; sub(/^  /,""); print}' <<<"$line")

    full="$RES_DIR/$expected_path"
    if [[ ! -f "$full" ]]; then
      warn "listed file missing: $expected_path"
      mismatch=$((mismatch + 1))
      continue
    fi
    actual=$(shasum -a 256 "$full" | awk '{print $1}')
    if [[ "$actual" != "$expected_hash" ]]; then
      warn "checksum drift on $expected_path"
      warn "  expected: $expected_hash"
      warn "  actual:   $actual"
      mismatch=$((mismatch + 1))
    fi
  done < "$CHECKSUMS"

  if (( mismatch == 0 )); then
    say "all checksums match."
  else
    warn "$mismatch file(s) drifted from the committed manifest."
    warn "This is a warning, not an error: upstream HuggingFace weights"
    warn "may have been updated. Review scripts/model-checksums.txt and"
    warn "regenerate it intentionally for reproducible release builds."
  fi
fi

say "done. Total files staged in $RES_DIR"
