#!/usr/bin/env bash
#
# scripts/download-models.sh
#
# Fetch the Kokoro TTS model weights and voice embeddings into
# upstream-kokoro/Resources/, then verify SHA256 hashes against a committed
# manifest. This is a thin wrapper around the upstream repo's existing
# download script — the upstream script is canonical; we add verification
# and staging for DMG packaging.
#
# Usage:
#   scripts/download-models.sh                     # fetch + strict verify (CI/release path)
#   VERIFY_ONLY=1 scripts/download-models.sh       # skip fetch, re-verify only
#   scripts/download-models.sh --allow-mismatch    # fetch + warn-on-mismatch (manifest refresh)
#   ALLOW_MISMATCH=1 scripts/download-models.sh    # same, via env var
#
# Exit codes:
#   0  — success (all required files present, checksums match, or baseline written)
#   1  — main model file missing after fetch
#   2  — prerequisite tooling missing
#   3  — checksum mismatch in strict mode
#
# See scripts/model-checksums.txt for the manifest format.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
UPSTREAM_DIR="$REPO_ROOT/upstream-kokoro"
RES_DIR="$UPSTREAM_DIR/Resources"
CHECKSUMS="$SCRIPT_DIR/model-checksums.txt"

say() { printf '[download-models] %s\n' "$*"; }
warn() { printf '[download-models] WARN: %s\n' "$*" >&2; }
die()  { printf '[download-models] ERROR: %s\n' "$*" >&2; exit "${2:-1}"; }

# ---------- flag parsing -------------------------------------------------
ALLOW_MISMATCH="${ALLOW_MISMATCH:-0}"
for arg in "$@"; do
  case "$arg" in
    --allow-mismatch) ALLOW_MISMATCH=1 ;;
    -h|--help)
      sed -n '3,22p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) die "unknown argument: $arg" 2 ;;
  esac
done

# ---------- prerequisite checks -----------------------------------------
command -v shasum  >/dev/null 2>&1 || die "shasum not found (part of macOS base)" 2
command -v make    >/dev/null 2>&1 || die "make not found"                        2
command -v python3 >/dev/null 2>&1 || die "python3 not found (ships with macOS)"  2

# Portable `realpath --relative-to` replacement. GNU coreutils realpath is
# not available on stock macOS; python3 is already a hard dep for the
# project, so use os.path.relpath which produces identical output for the
# absolute, existing paths this script computes.
relpath() {
  # $1 = target, $2 = start
  python3 -c 'import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$1" "$2"
}

# ---------- fetch ---------------------------------------------------------
if [[ "${VERIFY_ONLY:-0}" != "1" ]]; then
  if [[ ! -d "$UPSTREAM_DIR" ]]; then
    die "upstream-kokoro missing at $UPSTREAM_DIR (did you clone with --recurse-submodules?)"
  fi
  say "delegating to upstream: cd upstream-kokoro && make download-models"
  ( cd "$UPSTREAM_DIR" && make download-models )
  say "upstream download complete."
fi

# ---------- existence check ----------------------------------------------
MAIN_MODEL="$RES_DIR/kokoro-v1_0.safetensors"
if [[ ! -f "$MAIN_MODEL" ]]; then
  die "main model file missing: $MAIN_MODEL" 1
fi

VOICE_DIR="$RES_DIR/voices"
if [[ ! -d "$VOICE_DIR" ]]; then
  warn "voices/ directory is empty or missing at $VOICE_DIR"
fi

# ---------- hash computation --------------------------------------------
declare -a CURRENT_HASHES=()

# Main safetensors
H=$(shasum -a 256 "$MAIN_MODEL" | awk '{print $1}')
CURRENT_HASHES+=("$H  kokoro-v1_0.safetensors")

# Voices
shopt -s nullglob
for f in "$VOICE_DIR"/*.safetensors; do
  name="voices/$(basename "$f")"
  H=$(shasum -a 256 "$f" | awk '{print $1}')
  CURRENT_HASHES+=("$H  $name")
done
shopt -u nullglob

say "computed hashes for ${#CURRENT_HASHES[@]} file(s)"

# ---------- verify / write baseline --------------------------------------
#
# The manifest lives at scripts/model-checksums.txt. If every entry is a
# TODO/empty placeholder (no concrete 64-hex hash lines), we write the
# current hashes as the baseline and exit 0 — this is the first-time
# bootstrap path.
#
# Otherwise we verify strictly: any missing file or hash drift is a hard
# failure (exit 3). This is the CI/release default. To intentionally
# refresh the manifest after an upstream revision bump, re-run with
# `--allow-mismatch` (or ALLOW_MISMATCH=1), confirm the diff, and commit
# the new hashes.

is_baseline_empty=true
if [[ -f "$CHECKSUMS" ]]; then
  if grep -Eq '^[0-9a-f]{64}  ' "$CHECKSUMS"; then
    is_baseline_empty=false
  fi
fi

if $is_baseline_empty; then
  say "manifest has no concrete hashes yet — writing baseline to $CHECKSUMS"
  verify_rel=$(relpath "$CHECKSUMS" "$RES_DIR")
  {
    printf '# freekoko model checksums (SHA-256)\n'
    printf '# Generated by scripts/download-models.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# Verify with: cd upstream-kokoro/Resources && shasum -a 256 -c %s\n' "$verify_rel"
    printf '#\n'
    printf '# To refresh: delete the hash lines below and re-run scripts/download-models.sh\n'
    printf '#\n\n'
    printf '%s\n' "${CURRENT_HASHES[@]}"
  } > "$CHECKSUMS"
  say "baseline manifest written (${#CURRENT_HASHES[@]} entries)."
else
  say "verifying against existing manifest..."
  mismatch=0
  while IFS= read -r line; do
    # Skip comments/blank
    [[ -z "${line// }" ]] && continue
    [[ "$line" =~ ^# ]] && continue

    expected_hash=$(awk '{print $1}' <<<"$line")
    # Path is everything after "<hash>  " (hash + two spaces, per shasum format).
    # Stripping just "$1 " leaves a leading space; use a regex split instead.
    expected_path=${line#${expected_hash}  }

    full="$RES_DIR/$expected_path"
    if [[ ! -f "$full" ]]; then
      warn "listed file missing: $expected_path"
      mismatch=$((mismatch + 1))
      continue
    fi
    actual=$(shasum -a 256 "$full" | awk '{print $1}')
    if [[ "$actual" != "$expected_hash" ]]; then
      warn "checksum drift on $expected_path"
      warn "  expected: $expected_hash"
      warn "  actual:   $actual"
      mismatch=$((mismatch + 1))
    fi
  done < "$CHECKSUMS"

  if (( mismatch == 0 )); then
    say "all checksums match."
  else
    if [[ "$ALLOW_MISMATCH" == "1" ]]; then
      warn "$mismatch file(s) drifted from the committed manifest."
      warn "Continuing because --allow-mismatch was passed. If you are"
      warn "intentionally refreshing the manifest, delete the hash lines"
      warn "in $CHECKSUMS and re-run this script to regenerate them."
    else
      warn "$mismatch file(s) drifted from the committed manifest."
      warn "This is a fatal error in strict mode (the default)."
      warn "If you are intentionally refreshing the manifest after an"
      warn "upstream revision bump, re-run with --allow-mismatch, verify"
      warn "the diff, and commit the new $CHECKSUMS."
      die "checksum verification failed ($mismatch mismatch(es))" 3
    fi
  fi
fi

say "done. Total files staged in $RES_DIR"
